/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ExportarRouteImport } from './routes/exportar'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAssistenteRouteImport } from './routes/app.assistente'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppCatalogoRouteImport } from './routes/app.catalogo'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'
import { Route as AppIntegracoesRouteImport } from './routes/app.integracoes'
import { Route as AppPdvRouteImport } from './routes/app.pdv'
import { Route as AppUnidadesRouteImport } from './routes/app.unidades'
import { Route as AppVendasRouteImport } from './routes/app.vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportarRoute = ExportarRouteImport.update({
  id: '/exportar',
  path: '/exportar',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistenteRoute = AppAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPdvRoute = AppPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AppRoute,
} as any)
const AppUnidadesRoute = AppUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/exportar': typeof ExportarRoute
  '/loja': typeof LojaRoute
  '/recuperar': typeof RecuperarRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/exportar': typeof ExportarRoute
  '/loja': typeof LojaRoute
  '/recuperar': typeof RecuperarRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/app/vendas': typeof AppVendasRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/exportar': typeof ExportarRoute
  '/loja': typeof LojaRoute
  '/recuperar': typeof RecuperarRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalogo': typeof AppCatalogoRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/exportar'
    | '/loja'
    | '/recuperar'
    | '/app/assistente'
    | '/app/auditoria'
    | '/app/catalogo'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/equipe'
    | '/app/integracoes'
    | '/app/pdv'
    | '/app/unidades'
    | '/app/vendas'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/exportar'
    | '/loja'
    | '/recuperar'
    | '/app/assistente'
    | '/app/auditoria'
    | '/app/catalogo'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/equipe'
    | '/app/integracoes'
    | '/app/pdv'
    | '/app/unidades'
    | '/app/vendas'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/exportar'
    | '/loja'
    | '/recuperar'
    | '/app/assistente'
    | '/app/auditoria'
    | '/app/catalogo'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/equipe'
    | '/app/integracoes'
    | '/app/pdv'
    | '/app/unidades'
    | '/app/vendas'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ExportarRoute: typeof ExportarRoute
  LojaRoute: typeof LojaRoute
  RecuperarRoute: typeof RecuperarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exportar': {
      id: '/exportar'
      path: '/exportar'
      fullPath: '/exportar'
      preLoaderRoute: typeof ExportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistente': {
      id: '/app/assistente'
      path: '/assistente'
      fullPath: '/app/assistente'
      preLoaderRoute: typeof AppAssistenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalogo': {
      id: '/app/catalogo'
      path: '/catalogo'
      fullPath: '/app/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integracoes': {
      id: '/app/integracoes'
      path: '/integracoes'
      fullPath: '/app/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pdv': {
      id: '/app/pdv'
      path: '/pdv'
      fullPath: '/app/pdv'
      preLoaderRoute: typeof AppPdvRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/unidades': {
      id: '/app/unidades'
      path: '/unidades'
      fullPath: '/app/unidades'
      preLoaderRoute: typeof AppUnidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendas': {
      id: '/app/vendas'
      path: '/vendas'
      fullPath: '/app/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistenteRoute: typeof AppAssistenteRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCatalogoRoute: typeof AppCatalogoRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppPdvRoute: typeof AppPdvRoute
  AppUnidadesRoute: typeof AppUnidadesRoute
  AppVendasRoute: typeof AppVendasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistenteRoute: AppAssistenteRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCatalogoRoute: AppCatalogoRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppPdvRoute: AppPdvRoute,
  AppUnidadesRoute: AppUnidadesRoute,
  AppVendasRoute: AppVendasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ExportarRoute: ExportarRoute,
  LojaRoute: LojaRoute,
  RecuperarRoute: RecuperarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
